-- Insert 50 starter questions into question_bank
INSERT INTO question_bank (prompt, label_left, label_right, times_used, submitted_by) VALUES
  ('How do you prefer to spend your weekend?', 'Out with friends', 'Alone at home', 0, 'System'),
  ('What''s your ideal vacation?', 'Beach resort', 'Mountain adventure', 0, 'System'),
  ('How do you handle conflict?', 'Confront directly', 'Avoid and reflect', 0, 'System'),
  ('What''s your work style?', 'Collaborate', 'Work independently', 0, 'System'),
  ('How do you make decisions?', 'Logic and data', 'Gut feeling', 0, 'System'),
  ('What''s your morning routine like?', 'Rushed and chaotic', 'Calm and planned', 0, 'System'),
  ('How do you learn best?', 'Reading and studying', 'Doing and experiencing', 0, 'System'),
  ('What''s your ideal Friday night?', 'Wild party', 'Quiet dinner', 0, 'System'),
  ('How do you express yourself?', 'Words and writing', 'Actions and deeds', 0, 'System'),
  ('What drives you most?', 'Success and achievement', 'Happiness and balance', 0, 'System'),
  ('How do you handle stress?', 'Talk it out', 'Process alone', 0, 'System'),
  ('What''s your spending style?', 'Save for future', 'Enjoy the present', 0, 'System'),
  ('How do you approach new ideas?', 'Skeptical', 'Enthusiastic', 0, 'System'),
  ('What''s your communication style?', 'Direct and brief', 'Detailed and thorough', 0, 'System'),
  ('How do you recharge?', 'Social activities', 'Solitude', 0, 'System'),
  ('What''s your planning approach?', 'Spontaneous', 'Carefully planned', 0, 'System'),
  ('How do you view rules?', 'Guidelines to bend', 'Standards to follow', 0, 'System'),
  ('What''s your risk tolerance?', 'Play it safe', 'Take big risks', 0, 'System'),
  ('How do you handle criticism?', 'Take it personally', 'Use it constructively', 0, 'System'),
  ('What''s your debate style?', 'Win at all costs', 'Find common ground', 0, 'System'),
  ('How do you approach problems?', 'Big picture first', 'Details first', 0, 'System'),
  ('What''s your time perception?', 'Always late', 'Always early', 0, 'System'),
  ('How do you show affection?', 'Physical touch', 'Words of affirmation', 0, 'System'),
  ('What''s your entertainment preference?', 'Fiction and fantasy', 'Documentary and reality', 0, 'System'),
  ('How do you handle change?', 'Resist it', 'Embrace it', 0, 'System'),
  ('What''s your food philosophy?', 'Eat to live', 'Live to eat', 0, 'System'),
  ('How do you approach fitness?', 'Competitive sports', 'Solo workouts', 0, 'System'),
  ('What''s your music taste?', 'Classic and familiar', 'New and experimental', 0, 'System'),
  ('How do you organize your space?', 'Messy and chaotic', 'Neat and organized', 0, 'System'),
  ('What''s your social media usage?', 'Constantly connected', 'Rarely online', 0, 'System'),
  ('How do you give feedback?', 'Blunt and honest', 'Gentle and tactful', 0, 'System'),
  ('What''s your creativity outlet?', 'Artistic expression', 'Logical problem-solving', 0, 'System'),
  ('How do you handle deadlines?', 'Last minute rush', 'Well ahead of time', 0, 'System'),
  ('What''s your leadership style?', 'Delegate tasks', 'Lead by example', 0, 'System'),
  ('How do you view tradition?', 'Respect and preserve', 'Question and evolve', 0, 'System'),
  ('What''s your phone usage?', 'Always available', 'Often unreachable', 0, 'System'),
  ('How do you approach relationships?', 'Many acquaintances', 'Few close friends', 0, 'System'),
  ('What''s your humor style?', 'Sarcastic and dry', 'Light and playful', 0, 'System'),
  ('How do you handle success?', 'Celebrate loudly', 'Acknowledge quietly', 0, 'System'),
  ('What''s your movie preference?', 'Happy endings', 'Realistic endings', 0, 'System'),
  ('How do you approach fashion?', 'Comfort first', 'Style first', 0, 'System'),
  ('What''s your travel style?', 'Planned itinerary', 'Go with the flow', 0, 'System'),
  ('How do you show appreciation?', 'Give gifts', 'Spend quality time', 0, 'System'),
  ('What''s your reading preference?', 'Digital screens', 'Physical books', 0, 'System'),
  ('How do you handle mistakes?', 'Move on quickly', 'Reflect deeply', 0, 'System'),
  ('What''s your work-life balance?', 'Work is life', 'Life outside work', 0, 'System'),
  ('How do you approach competition?', 'Thrives on it', 'Avoids it', 0, 'System'),
  ('What''s your pet preference?', 'Dogs', 'Cats', 0, 'System'),
  ('How do you handle surprises?', 'Love them', 'Prefer to know', 0, 'System'),
  ('What''s your ideal group size?', 'Large groups', 'Small intimate groups', 0, 'System');
